{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Endpoint (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests per Endpoint (Table)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Avg Payload Size per Endpoint",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_response_size_bytes_sum) by (handler) / sum(http_response_size_bytes_count) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Latency (Avg & P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "Avg {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler))",
     "legendFormat": "P99 {{handler}}"
    }
   ]
  },
  {
   "title": "Total Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "API Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "up{job='fastapi'}", "legendFormat": "API Up (1=Yes, 0=No)" }
   ]
  }
 ]
}